# Site settings
title: Mat's Web Tech Blog
email: mat@wibbly.org.uk
description: > # this means to ignore newlines until "baseurl:"
  The personal, web-tech-related, blog of Mat Scales.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matscales.com" # the base hostname & protocol for your site
twitter_username: wibblymat
github_username:  wibblymat

# Build settings
markdown: kramdown
